/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_Hello */

#ifndef _Included_com_example_jni_Hello
#define _Included_com_example_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_Hello
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jni_Hello_getName(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
